feat: 나의 게시글 목록 조회 기능 구현
SSAF-SOUND/ssaf-sound-be pull request #109
Opened 2023-07-03 10:11 UTC by jjuny0310

## Issues

- #97 

## 구분

- [ ] 버그 수정
- [x] 기능 추가
- [x] 코드 리팩터링
- [ ] 문서 업데이트
- [ ] 기타

## 주요 변경점

- 나의 게시글 목록 조회 기능 구현
- post, hotpost 단방향 관계로 수정(연쇄 삭제 직접 구현)
- 자신의 게시글은 신고 못하도록 수정
- 빈 게시판 예외 삭제
- 일부 dto 네이밍 수정

## 기타

2023-07-03 10:36 UTC, moonn6pence requested changes

2023-07-03 10:36 UTC, moonn6pence commented on src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
> +    NOT_REPORT_MY_POST("805", "자신의 게시글은 신고할 수 없습니다."),
UNABLE_REPORT_MY_POST 어떨까요?

2023-07-03 10:36 UTC, moonn6pence commented on src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
> +        }
작성한 글이 없어서 0개가 조회되는 경우는 정상적인 경우가 아닐까요?

2023-07-03 10:36 UTC, moonn6pence commented on src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
>                  .orElseThrow(() -> new PostException(PostErrorInfo.NOT_FOUND_POST));
삭제 순서가 게시글 삭제 -> 핫게시글 삭제로 가야하지 않을까요? 지금 로직은 존재하지 않은 postId 라면 무조건 두 번의 쿼리를 호출하지 않을까요?

2023-07-03 10:43 UTC, jjuny0310 commented on src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
> +    NOT_REPORT_MY_POST("805", "자신의 게시글은 신고할 수 없습니다."),
반영했습니다!

2023-07-03 10:44 UTC, jjuny0310 commented on src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
> +        }
정상적인 경우지만, 게시글 없다는 메시지를 주기 위해서 입니다.

2023-07-03 10:47 UTC, moonn6pence approved these changes

2023-07-03 11:04 UTC, moonn6pence commented on src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
> +        }
프론트 분들과 협의해서 정하는게 나을 것 같습니다.

2023-07-03 11:09 UTC, khs960616 approved these changes

2023-07-03 15:30 UTC, YongsHub approved these changes

2023-07-04 02:02 UTC, jjuny0310 commented on src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
> +    @EntityGraph(attributePaths = {"board", "member"})
>EntityGraph를 활용하실때 제가 생각했을때는 Outer Join때문에 사용하신거 같은데 어떤 관점에서 구분해서 사용하시는지 궁금해요!

제가 EntityGraph를 사용한 이유는 fetch join을 위해서 사용했습니다. 현재 EntityGraph를 사용할만한 기능은 3가지가 있는데 현재 2개 기능에 적용했습니다.
1. 게시글 목록 조회
2. 핫게시글 목록 조회
3. 나의 게시글 목록 조회

1번과 3번에만 EntityGraph를 적용했는데 3개의 기능 모두 fetch join을 사용하기 위함으로 쿼리 동작 자체는 동일하지만, 가능하면 EntityGraph를 적용하려고 했어요
2번 기능에 EntityGraph를 사용하지 않은 이유는 hotpost안에 있는걸 조인하는것이 아닌, hotpost안에 있는 post안에 있는걸 조인하기 위해서입니다. 이 상황에서는 EntityGraph가 적용되지 않더라구요

**결론은 가능하면 fetch join에 EntityGraph를 적용하려고 하지만, 적용하기에 어려움이 있는 쿼리문에 경우에는 직접 fetch join을 작성하고 있습니다.**

2023-07-04 02:02 UTC, merged

2023-07-04 03:33 UTC, YongsHub commented on src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
> +    @EntityGraph(attributePaths = {"board", "member"})
아하 넵!
근데 제가 알기로는 단순히 fetch join을 위해 사용하면 문제가 발생할 확률이 높다고 하네요! 필요에 따라서 직접 fetch join을 사용할 경우 inner join, EntityGraph를 사용하는 경우 outer join때문에 원하는 쿼리 결과가 달라질 수 있을 것 같아요 👍 
https://docs.spring.io/spring-data/data-jpa/docs/current/api/org/springframework/data/jpa/repository/EntityGraph.EntityGraphType.html#FETCH